generate:
    script:
        - npm install
        - node ./quicktype.js
        - mkdir temp
        - cd temp
        - echo ${API_GENERATOR_TOKEN}
        - git clone https://Timo.Molls:${API_GENERATOR_TOKEN}@gitlab.enet.local/Timo.Molls/java-api-code.git
        - rm -r java-api-code/bo4e
        - mv ../bo4e java-api-code
        - cd java-api-code
        - git add .
        - git commit -m "Update bo4e"
        - git push origin master
