stages:
    - build
    - setup_git
    - deploy_git

build-job:
    stage: build
    image: node
    script:
        - npm install
        - node ./quicktype.js
    artifacts:
        paths:
            - "bo4e/"
        untracked: false
        when: on_success
        expire_in: 1 day

clone:
    stage: setup_git
    dependencies:
        - "build-job"
    script:
        - git clone https://Timo.Molls:${API_GENERATOR_TOKEN}@gitlab.enet.local/Timo.Molls/java-api-code.git
        - ls
        - rm -r java-api-code/bo4e
        - mv bo4e java-api-code
    artifacts:
        paths:
            - "java-api-code"
        untracked: false
        when: on_success
        expire_in: 1 day
    
commit:
    stage: deploy_git
    dependencies:
        - "clone"
    script:
        - cd java-api-code
        - git add .
        - git commit -m "Update bo4e"
        - git push origin master
    allow_failure: true
