generate:
    script:
        - npm install
        - node ./quicktype.js
        - git init
        - git remote add origin https://gitlab.enet.local/Timo.Molls/java-api-code.git
        - git branch -M master
        - git push -uf origin master

