name: 'Generate Java Classes'
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        default: latest
        required: true
  workflow_call:
    inputs:
      version:
        type: string
        default: latest
        required: false
    secrets:
      ACCESS_TOKEN_JAVA_API:
        required: true
      CREATE_RELEASE_TOKEN:
        required: true
jobs:
  generation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 18.17.x
          cache: npm
      - name: Install
        run: npm install
      - name: Get Schemas
        id: schemas
        env:
          VERSION: ${{ inputs.version }}
        run: |
          echo $VERSION
          [[ `echo $VERSION | grep -c "rc"` -gt 0 || `echo $VERSION | grep -oE "^[0-9]{4}"` -lt 2024 ]] && echo "Achtung: kein offizieller Release"
          RELEASE="tags/v${VERSION}"
          [[ "latest" = "${VERSION}" ]] 2>/dev/null && RELEASE="latest"
          echo $RELEASE
          curl -s "https://api.github.com/repos/bo4e/BO4E-Schemas/releases/${RELEASE}" > releasedata
          if [[ `grep -c "tarball_url" releasedata` -gt 0 ]]
          then
            RELEASETAG=`grep "\"tag_name\":" releasedata | cut -d : -f2 | tr -d "\", "`
            [[ $VERSION = latest ]] && [[ `echo $RELEASETAG | grep -c "rc"` -gt 0 || `echo $RELEASETAG | tr -d "v" | grep -oE "^[0-9]{4}"` -lt 2024 ]] && RELEASETAG='invalid'
            echo $RELEASETAG
            echo "TAGNAME=$RELEASETAG" >> "$GITHUB_OUTPUT"
            [[ $RELEASETAG = invalid ]] && echo "Kein offizieller Release" && exit 0
            grep "tarball_url" releasedata | cut -d : -f 2,3 | tr -d \", | wget -qi - --output-document=temp
            if tar -xf temp
            then
              TARDIR=$(tar -tf temp | grep -i "^[a-z|0-9|-]*/$")
              rm -rf ./bo4e_schemas && mv "${TARDIR}src/bo4e_schemas" .
            else
              echo "Could not unpack archive"
              exit 1
            fi
          else
            echo "Could not find tarball_url"
            exit 1
          fi
      - name: Generate
        if: ${{ steps.schemas.outputs.TAGNAME != 'invalid' }}
        run: |
          [[ -d bo4e_schemas ]] && node ./quicktype.js
      - name: Push changes
        if: ${{ steps.schemas.outputs.TAGNAME != 'invalid' }}
        uses: cpina/github-action-push-to-another-repository@v1.7.2
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACCESS_TOKEN_JAVA_API }}
        with:
          source-directory: "bo4e"
          target-directory: "bo4e"
          destination-github-username: "TimoMolls"
          destination-repository-name: "BO4E-Java"
          user-email: timo.molls@enet.eu
          target-branch: master
          commit-message: "Update JAVA-Classes - BO4E ${{ steps.schemas.outputs.TAGNAME }}"
      - name: Create Release
        if: ${{ steps.schemas.outputs.TAGNAME != 'invalid' }}
        env:
          TOKEN: ${{ secrets.CREATE_RELEASE_TOKEN }}
          VERSION: ${{ steps.schemas.outputs.TAGNAME }}
        run: node ./create_release.js "$TOKEN" "$VERSION"
