name: 'Generate Java Classes'
on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
jobs:
  generation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 16.20.x
          cache: npm
      - name: Install
        run: npm install
      - name: Get Schemas
        run: |
          git clone https://github.com/bo4e/BO4E-Schemas.git
          cd BO4E-Schemas
          ls
      - name: Generate
        run: node ./quicktype_v2.js
      - name: Push changes
        uses: cpina/github-action-push-to-another-repository@v1.7.2
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACCESS_TOKEN_JAVA_API }}
        with:
          source-directory: "bo4e"
          target-directory: "bo4e"
          destination-github-username: "TimoMolls"
          destination-repository-name: "java-api-code"
          user-email: timo.molls@enet.eu
          target-branch: master
          commit-message: "Update bo4e"
