name: 'Testing generation'
on:
  push:
    branches:
      - master
jobs:
  generation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 16.20.x
          cache: npm
      - name: Install
        run: npm install
      - name: Generate
        run: node ./quicktype.js
      - name: Push changes
        run: |
          cd generatedCode
          git init
          git add bo4e
          git commit -m "updated bo4e"
          git remote add origin https://github.com/TimoMolls/java-api-code.git
          git branch -M main
          git push -u origin main
