# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        default: latest
jobs:
  generation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Get Schemas
        env: 
          VERSION: ${{ inputs.version }}
        run: |
          RELEASE="tags/${VERSION}"
          if [[ $VERSION -eq "latest" ]]
          then RELEASE="latest"
          fi
          curl -s https://api.github.com/repos/bo4e/BO4E-Schemas/releases/${RELEASE} | grep "tarball_url" | cut -d : -f 2,3 | tr -d \", | wget -qi - --output-document=temp
          tar -xf temp
          TARDIR=$(tar -tf temp | grep -i "^[a-z|0-9|-]*/$")
          date
          rm -r ./bo4e_schemas && mv "${TARDIR}src/bo4e_schemas" . && cd bo4e_schemas && ls -l
