# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        default: latest
jobs:
  generation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Get Schemas
        env: 
          VERSION: ${{ inputs.version }}
        run: |
          [[ `echo $VERSION | grep -c "rc"` -gt 0 || `echo $VERSION | grep -oE "^[0-9]{4}"` -lt 2024 ]] && echo "Kein offizieller Release" && exit 0
          RELEASE="tags/v${VERSION}"
          [[ "vlatest" -eq "v${VERSION}" ]] 2>/dev/null && RELEASE="latest"
          curl -s "https://api.github.com/repos/bo4e/BO4E-Schemas/releases/${RELEASE}" > releasedata
          if [[ `grep -c "" releasedata` -gt 0 ]]
          then
            grep "tarball_url" releasedata | cut -d : -f 2,3 | tr -d \", | wget -qi - --output-document=temp
            if tar -xf temp
            then
              TARDIR=$(tar -tf temp | grep -i "^[a-z|0-9|-]*/$")
              rm -rf ./bo4e_schemas && mv "${TARDIR}src/bo4e_schemas" . && cd bo4e_schemas && ls -l
            else
              echo "Could not unpack archive"
              exit 5
            fi
          else
            echo "Could not find tarball_url"
            exit 5
          fi
