name: 'Synchronise Releases'
on: 
  workflow_dispatch
jobs:
  synchronisation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 18.17.x
          cache: npm
      - name: Install
        run: npm install
      - name: Synch
        env:
          TOKEN: ${{ secrets.CREATE_RELEASE_TOKEN }}
        run: |
          TAG=`node ./synch_releases.js $TOKEN`
          echo $TAG
